# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: wtf-fastapi_test_db
    image: postgres:14.5-alpine
    restart: 'no'
    environment:
      POSTGRES_DB: banned
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
      POSTGRES_USER: dbo
    ports:
      - 5432:5432
    volumes:
      - "~/.cache/testdbs/wtf-fastapi_test_db:/var/lib/postgresql/data"

  adminer:
    image: adminer-wtf-fastapi_test_db
    restart: no
    ports:
      - 8080:8080
