# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: quotes_test_db
    image: postgres:14.5-alpine
    restart: 'no'
    environment:
      POSTGRES_DB: banned
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
      POSTGRES_USER: dbo
    ports:
      - 5432:5432
    volumes:
      - "./testdbdata:/var/lib/postgresql/data"
